run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - gosec
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gofumpt
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - scopelint
    - gocritic
    - gochecknoinits
    - gochecknoglobals
    - godox
    - funlen
    - gocognit
    - nestif
    - godot
    - testpackage
    - nolintlint
    - exportloopref
    - exhaustive
    - sqlclosecheck
    - rowserrcheck
    - noctx
    - gomodguard
    - asciicheck
    - bidichk
    - durationcheck
    - errorlint
    - forbidigo
    - makezero
    - predeclared
    - revive
    - tagliatelle
    - thelper
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 15
  dupl:
    threshold: 100
  funlen:
    lines: 80
    statements: 40
  gocognit:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  godot:
    capital: true
  godox:
    keywords:
      - TODO
      - FIXME
      - BUG
  goimports:
    local-prefixes: github.com/naoyafurudono/sqlc-use-analysis
  gosec:
    severity: medium
    confidence: medium
  lll:
    line-length: 120
  misspell:
    locale: US
  nestif:
    min-complexity: 6
  nolintlint:
    require-explanation: true
    require-specific: true
  prealloc:
    simple: true
    range-loops: true
    for-loops: true
  testpackage:
    skip-regexp: (export|internal)_test\.go
  unparam:
    check-exported: true
  unused:
    check-exported: false
  whitespace:
    multi-if: true
    multi-func: true
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gocognit
        - gocyclo
        - gosec
        - lll
        - wrapcheck
    - path: test/fixtures/
      linters:
        - lll
        - dupl
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals