package types

import "time"

// DependencyResult represents the complete analysis result
type DependencyResult struct {
	Metadata     Metadata                   `json:"metadata"`
	FunctionView map[string][]TableAccess   `json:"function_view"`
	TableView    map[string][]FunctionAccess `json:"table_view"`
}

// Metadata contains analysis metadata
type Metadata struct {
	GeneratedAt   time.Time `json:"generated_at"`
	Version       string    `json:"version"`
	TotalFuncs    int       `json:"total_functions"`
	TotalTables   int       `json:"total_tables"`
	AnalysisDuration time.Duration `json:"analysis_duration"`
}

// TableAccess represents table access from a function
type TableAccess struct {
	Table      string   `json:"table"`
	Operations []string `json:"operations"`
}

// FunctionAccess represents function access to a table
type FunctionAccess struct {
	Function   string   `json:"function"`
	Operations []string `json:"operations"`
}

// SQLMethodInfo represents information about a sqlc-generated method
type SQLMethodInfo struct {
	MethodName string          `json:"method_name"`
	Tables     []TableOperation `json:"tables"`
}

// TableOperation represents an operation on a table
type TableOperation struct {
	TableName  string   `json:"table_name"`
	Operations []string `json:"operations"`
}

// GoFunctionInfo represents information about a Go function
type GoFunctionInfo struct {
	FullName      string     `json:"full_name"`
	PackagePath   string     `json:"package_path"`
	FunctionName  string     `json:"function_name"`
	Receiver      string     `json:"receiver,omitempty"`
	FilePath      string     `json:"file_path"`
	StartLine     int        `json:"start_line"`
	EndLine       int        `json:"end_line"`
	DirectCalls   []string   `json:"direct_calls"`
	AllCalls      []string   `json:"all_calls"`
}

// CallInfo represents a function call
type CallInfo struct {
	PackagePath string `json:"package_path"`
	FuncName    string `json:"func_name"`
	Line        int    `json:"line"`
}

// GeneratedFile represents a file generated by the plugin
type GeneratedFile struct {
	Name     string `json:"name"`
	Contents []byte `json:"contents"`
}